---
- name: 'Ensure Wireguard userland tools and dependencies'
  ansible.builtin.package:
    name:
      - 'wireguard-tools'
    update_cache: true

- name: 'Ensure Wireguard userland tools on controller'
  ansible.builtin.package:
    name:
      - 'wireguard-tools'
    update_cache: true
  delegate_to: 'localhost'
  run_once: true
  become: true

- name: 'Ensure config snippet dir'
  ansible.builtin.file:
    path: "{{ wireguard_basedir }}/{{ wg_int['name'] }}.conf.d"
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0700'
  loop: "{{ wireguard_interfaces }}"
  no_log: "{{ wireguard_no_log }}"
  loop_control:
    loop_var: 'wg_int'

- name: 'Ensure interface config'
  ansible.builtin.template:
    src: 'interface.conf.j2'
    dest: "{{ wireguard_basedir }}/{{ wg_int['name'] }}.conf.d/00_interface.conf"
    owner: 'root'
    group: 'root'
    mode: '0600'
  no_log: "{{ wireguard_no_log }}"
  loop: "{{ wireguard_interfaces }}"
  loop_control:
    loop_var: 'wg_int'

- name: 'Ensure peer config'
  ansible.builtin.template:
    src: 'peer.conf.j2'
    dest: "{{ wireguard_basedir }}/{{ wg_peer['name'] }}.conf.d/01_peers.conf"
    owner: 'root'
    group: 'root'
    mode: '0600'
  no_log: "{{ wireguard_no_log }}"
  loop: "{{ wireguard_interfaces }}"
  loop_control:
    loop_var: 'wg_peer'

- name: 'Assemble config file'
  ansible.builtin.assemble:
    dest: "{{ wireguard_basedir }}/{{ wg_int['name'] }}.conf"
    src: "{{ wireguard_basedir }}/{{ wg_int['name'] }}.conf.d"
    owner: 'root'
    group: 'root'
    mode: '0600'
  no_log: "{{ wireguard_no_log }}"
  loop: "{{ wireguard_interfaces }}"
  loop_control:
    loop_var: 'wg_int'
  notify: 'Reload wireguard'

- name: 'Ensure service'
  ansible.builtin.service:
    name: "wg-quick@{{ wg_int['name'] }}"
    state: 'started'
    enabled: true
  loop: "{{ wireguard_interfaces }}"
  no_log: "{{ wireguard_no_log }}"
  loop_control:
    loop_var: 'wg_int'
