---
- name: 'Ensure Wireguard userland tools and dependencies'
  apt:
    name:
      - 'wireguard-tools'
      - 'procps'
      - 'iptables'
    install_recommends: false

- name: 'Ensure Wireguard userland tools on controller'
  apt:
    name:
      - 'wireguard-tools'
    install_recommends: false
  delegate_to: 'localhost'
  run_once: true
  when: wireguard_molecule is not defined # this task does not work in Molecule

- name: 'Ensure Wireguard kernel module DKMS package'
  apt:
    name:
      - 'wireguard-dkms'
    install_recommends: false
  when:
    - ansible_facts['virtualization_type'] != 'lxc'
    - ansible_facts['kernel'] is version('5.6', 'lt')

- name: 'Ensure config snippet dir'
  file:
    path: "{{ wireguard_basedir }}/{{ wg_int['name'] }}.conf.d"
    state: 'directory'
    mode: 0700
    owner: 'root'
    group: 'root'
  loop: "{{ wireguard_interfaces }}"
  loop_control:
    loop_var: 'wg_int'

- name: 'Ensure interface config'
  template:
    src: 'interface.conf.j2'
    dest: "{{ wireguard_basedir }}/{{ wg_int['name'] }}.conf.d/00_interface.conf"
    mode: 0600
    owner: 'root'
    group: 'root'
  loop: "{{ wireguard_interfaces }}"
  loop_control:
    loop_var: 'wg_int'

- name: 'Ensure peer config'
  template:
    src: 'peer.conf.j2'
    dest: "{{ wireguard_basedir }}/{{ wg_peer['name'] }}.conf.d/01_peers.conf"
    mode: 0600
    owner: 'root'
    group: 'root'
  loop: "{{ wireguard_interfaces }}"
  loop_control:
    loop_var: 'wg_peer'

- name: 'Assemble config file'
  assemble:
    dest: "{{ wireguard_basedir }}/{{ wg_int['name'] }}.conf"
    src: "{{ wireguard_basedir }}/{{ wg_int['name'] }}.conf.d"
    mode: 0600
    owner: 'root'
    group: 'root'
  loop: "{{ wireguard_interfaces }}"
  loop_control:
    loop_var: 'wg_int'
  notify: 'reload wireguard'

- name: 'Ensure service'
  service:
    name: "wg-quick@{{ wg_int['name'] }}"
    state: 'started'
    enabled: true
  loop: "{{ wireguard_interfaces }}"
  loop_control:
    loop_var: 'wg_int'
