---
- name: 'reload wireguard'
  service:
    name: "wg-quick@{{ wireguard_interface['name'] }}"
    state: 'reloaded'
  register: 'reloaded_wireguard'
  until: reloaded_wireguard | succeeded
  retries: 3 # When testing with Molecule in Docker, reloading doesn't always go in one go
  delay: 5
