---
- name: 'reload wireguard'
  service:
    name: "wg-quick@{{ wireguard_interface['name'] }}"
    state: 'reloaded'
  retries: 2 # When testing with Molecule in Docker, reloading doesn't always go in one go
  delay: 5
