---
- name: 'Converge'
  hosts: 'all'
  tasks:
    - name: 'Run role'
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  vars:
    wireguard_molecule: true
    wireguard_no_log: false
