---
- name: 'Verify'
  hosts: 'wireguard-client'
  gather_facts: false
  tasks:
    - name: 'Ping over Wireguard'
      ansible.builtin.shell: |
        ping -c5 192.168.1.1
      changed_when: false

- name: 'Verify'
  hosts: 'wireguard-client2'
  gather_facts: false
  tasks:
    - name: 'Ping over Wireguard'
      ansible.builtin.shell: |
        ping -c5 192.168.2.1
      changed_when: false

- name: 'Verify'
  hosts: 'wireguard'
  gather_facts: false
  tasks:
    - name: 'Ping wireguard-client over Wireguard'
      ansible.builtin.shell: |
        ping -c5 192.168.1.2
      changed_when: false
    - name: 'Ping wireguard-client2 over Wireguard'
      ansible.builtin.shell: |
        ping -c5 192.168.2.2
      changed_when: false
